"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const jsx_runtime_1 = require("react/jsx-runtime");
const ui_1 = require("@workspace/ui");
const shared_1 = require("@workspace/shared");
function App() {
    return ((0, jsx_runtime_1.jsx)("div", { className: "min-h-screen bg-background p-8", children: (0, jsx_runtime_1.jsxs)("div", { className: "max-w-4xl mx-auto space-y-8", children: [(0, jsx_runtime_1.jsxs)("header", { className: "text-center", children: [(0, jsx_runtime_1.jsx)("h1", { className: "text-4xl font-bold text-foreground mb-4", children: "The Eye" }), (0, jsx_runtime_1.jsx)("p", { className: "text-muted-foreground", children: "A bun workspace monorepo with shadcn styling" })] }), (0, jsx_runtime_1.jsxs)("main", { className: "space-y-6", children: [(0, jsx_runtime_1.jsxs)("section", { className: "text-center", children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-2xl font-semibold mb-4", children: "Welcome" }), (0, jsx_runtime_1.jsxs)("p", { className: "text-muted-foreground mb-6", children: ["Current date: ", (0, shared_1.formatDate)(new Date())] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex gap-4 justify-center", children: [(0, jsx_runtime_1.jsx)(ui_1.Button, { children: "Get Started" }), (0, jsx_runtime_1.jsx)(ui_1.Button, { variant: "outline", children: "Learn More" })] })] }), (0, jsx_runtime_1.jsxs)("section", { className: "grid grid-cols-1 md:grid-cols-3 gap-6", children: [(0, jsx_runtime_1.jsxs)("div", { className: "p-6 border rounded-lg", children: [(0, jsx_runtime_1.jsx)("h3", { className: "font-semibold mb-2", children: "API" }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm text-muted-foreground", children: "Backend services running on port 3001" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "p-6 border rounded-lg", children: [(0, jsx_runtime_1.jsx)("h3", { className: "font-semibold mb-2", children: "Web" }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm text-muted-foreground", children: "Frontend application with React" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "p-6 border rounded-lg", children: [(0, jsx_runtime_1.jsx)("h3", { className: "font-semibold mb-2", children: "Packages" }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm text-muted-foreground", children: "Shared UI and utilities" })] })] })] })] }) }));
}
exports.default = App;
